reference_data_dir = 'reference'
sb_bad_star_name_ignore_filename = "bad_starname_ignore.csv"
sb_main_ref_filename = "simbad_main_ref_data.csv"
sb_save_filename =  "simbad_query_data.pkl"
sb_save_coord_filename = "simbad_coord_data.pkl"
sb_ref_filename =  "simbad_ref_data.txt"
tic_ref_filename = "tic_ref.csv"
sb_desired_names = ["2mass", "gaia dr2", "gaia dr1", "hd", "cd", "tyc", "hip", "gj", "hr", "bd", "ids", "tres", "gv",
                    "ngc", "bps", "ogle", "xo", 'kepler', "k2", "*", "**", "v*", "name", 'wds', 'hats']
